name: htdc
description: Packege with helpful flutter widgets and utils.
version: 0.0.1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  htdc_fade_button:
    git:
      url: git://github.com/HealthTechDevelopers/flutter_commons.git
      path: widgets/fade_button

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

